name = "codingchallenges"
version = "1.0.0"

description = "CodingChallenges' solutions in Gleam"
repository = { type = "github", user = "pdrmtaheri", repo = "codingchallenges" }
links = [{ title = "Coding Challenges", href = "https://codingchallenges.fyi" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"
shellout = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
